title: "VipeCollie's Blog"
description: "Blog de VipeCollie"
theme: jekyll-theme-cayman
baseurl: ""  
permalink: /:year/:month/:day/:title.html # Format des URLs des articles
show_downloads: true
google_analytics:  

markdown: kramdown
highlighter: rouge

